//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Project/Modules/PlayerAnchor/Scripts/Inputs/PlayerAnchorInputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace InputSystem
{
    public partial class @PlayerAnchorInputControls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerAnchorInputControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerAnchorInputControls"",
    ""maps"": [
        {
            ""name"": ""Land"",
            ""id"": ""65464c2a-640c-4dff-b71c-4fb41e7f02a7"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""7d7acd2a-6efd-442e-8d34-dbe1977bc43d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""fe2dd623-e0fe-4ae0-acb8-efea930e51e4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""c240019a-3d40-4d30-a865-8c21cc5c5238"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CancelAim"",
                    ""type"": ""Button"",
                    ""id"": ""ed4c441a-6c70-436c-adab-52f17a9f49f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""78022133-4efb-4377-af08-7b12a37d300e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickUp"",
                    ""type"": ""Button"",
                    ""id"": ""bd94e9a1-b31b-46cf-b77f-7b906b3fa22c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pull"",
                    ""type"": ""Button"",
                    ""id"": ""c65dcb9c-2172-44ae-ac42-7fcc00bdad4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""b5371a25-52a4-419e-8009-4afd4f2e9d11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kick"",
                    ""type"": ""Button"",
                    ""id"": ""77027586-2d0c-4667-9bc5-70b31877f699"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heal"",
                    ""type"": ""Button"",
                    ""id"": ""feeea9fc-b89a-470c-a6ea-4851ceb8406b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAttack_AnchorSpin"",
                    ""type"": ""Button"",
                    ""id"": ""4925b897-cadd-41d6-8352-231177a78d8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAttack_ChainSpikes"",
                    ""type"": ""Button"",
                    ""id"": ""32a26b19-085b-4773-8789-376a57e5547c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NullAction"",
                    ""type"": ""Button"",
                    ""id"": ""0b138e54-fc8d-441b-ba70-b8fec6bfd05e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2ca53492-ab53-46ab-9b2b-a1186fd64a69"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f2b026a-11f5-4ca1-bd17-af682875cbff"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7112c1b7-12f8-45a5-92ec-d31ff33472a4"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a68eb38b-af5b-4fe8-ab87-a68d758c1a88"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""PickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cd36bd9-17e1-4ce0-b008-bbd99baf169d"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": ""Desktop"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4323a02c-94c3-4eb0-8449-b31f775d2305"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": ""Desktop"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad71bada-d416-44b3-985e-64a9c58e44e2"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": ""Desktop"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b986edb1-554b-46b0-84a7-84f293eb4559"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": ""Desktop"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79e8283f-b9af-43e0-b4b6-cdd463fed519"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a1f3c3d-8e59-46ef-9ca8-de56c32863ed"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7dfa0d8f-c417-4b72-a5cc-85386756b77e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe1cfa72-5e1f-479f-a9fd-95e414c8291b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Heal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cd0a58c-a0d6-47c7-abb5-c4be184acf17"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""CancelAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9e47597-5bd6-418e-9f11-6fc898534f3b"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone"",
                    ""groups"": ""Desktop"",
                    ""action"": ""CancelAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3677d6a6-9cce-4e75-bccf-7f7c97bf9f31"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""SpecialAttack_AnchorSpin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10a6ce72-6902-46f7-8491-6382390e5ab0"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""NullAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dad2bb23-cbdb-4738-98a4-d0c52bcb05ff"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""SpecialAttack_ChainSpikes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""df36b836-b8bb-4955-b684-e65604e0347a"",
            ""actions"": [
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""077d1ec3-1b19-4ed1-94c7-5cd5417ede8f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenMenu"",
                    ""type"": ""Button"",
                    ""id"": ""4412f884-7b18-4796-a26c-d75d8b9d968a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Accept"",
                    ""type"": ""Button"",
                    ""id"": ""1f6cd8aa-0aa4-4186-8f93-751f4bb7abbb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""08fa1f6f-889e-48d4-af74-7565e667371e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug_UnlockMenu"",
                    ""type"": ""Button"",
                    ""id"": ""54e2f6f9-f6c5-4682-9a23-ef06e6c5e87c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3c82eaa3-705a-4893-8370-2c0961239ffd"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4161a199-6b29-4c31-a85c-0ff89eafb06f"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""OpenMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2c8d140-1ee0-4717-86df-556399e17911"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94f91014-5a07-4c4b-8c23-f5d50026949d"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""99c562ce-5567-4413-ab78-594ac06cffa4"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug_UnlockMenu"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""9806b4a8-bded-4b7f-a590-743bd560047e"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Debug_UnlockMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""d6defb04-de52-4439-84fa-31c3558a8a8e"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Debug_UnlockMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Desktop"",
            ""bindingGroup"": ""Desktop"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<DualShockGamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Land
            m_Land = asset.FindActionMap("Land", throwIfNotFound: true);
            m_Land_Move = m_Land.FindAction("Move", throwIfNotFound: true);
            m_Land_Look = m_Land.FindAction("Look", throwIfNotFound: true);
            m_Land_Aim = m_Land.FindAction("Aim", throwIfNotFound: true);
            m_Land_CancelAim = m_Land.FindAction("CancelAim", throwIfNotFound: true);
            m_Land_Throw = m_Land.FindAction("Throw", throwIfNotFound: true);
            m_Land_PickUp = m_Land.FindAction("PickUp", throwIfNotFound: true);
            m_Land_Pull = m_Land.FindAction("Pull", throwIfNotFound: true);
            m_Land_Dash = m_Land.FindAction("Dash", throwIfNotFound: true);
            m_Land_Kick = m_Land.FindAction("Kick", throwIfNotFound: true);
            m_Land_Heal = m_Land.FindAction("Heal", throwIfNotFound: true);
            m_Land_SpecialAttack_AnchorSpin = m_Land.FindAction("SpecialAttack_AnchorSpin", throwIfNotFound: true);
            m_Land_SpecialAttack_ChainSpikes = m_Land.FindAction("SpecialAttack_ChainSpikes", throwIfNotFound: true);
            m_Land_NullAction = m_Land.FindAction("NullAction", throwIfNotFound: true);
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_Back = m_UI.FindAction("Back", throwIfNotFound: true);
            m_UI_OpenMenu = m_UI.FindAction("OpenMenu", throwIfNotFound: true);
            m_UI_Accept = m_UI.FindAction("Accept", throwIfNotFound: true);
            m_UI_Quit = m_UI.FindAction("Quit", throwIfNotFound: true);
            m_UI_Debug_UnlockMenu = m_UI.FindAction("Debug_UnlockMenu", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Land
        private readonly InputActionMap m_Land;
        private List<ILandActions> m_LandActionsCallbackInterfaces = new List<ILandActions>();
        private readonly InputAction m_Land_Move;
        private readonly InputAction m_Land_Look;
        private readonly InputAction m_Land_Aim;
        private readonly InputAction m_Land_CancelAim;
        private readonly InputAction m_Land_Throw;
        private readonly InputAction m_Land_PickUp;
        private readonly InputAction m_Land_Pull;
        private readonly InputAction m_Land_Dash;
        private readonly InputAction m_Land_Kick;
        private readonly InputAction m_Land_Heal;
        private readonly InputAction m_Land_SpecialAttack_AnchorSpin;
        private readonly InputAction m_Land_SpecialAttack_ChainSpikes;
        private readonly InputAction m_Land_NullAction;
        public struct LandActions
        {
            private @PlayerAnchorInputControls m_Wrapper;
            public LandActions(@PlayerAnchorInputControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Land_Move;
            public InputAction @Look => m_Wrapper.m_Land_Look;
            public InputAction @Aim => m_Wrapper.m_Land_Aim;
            public InputAction @CancelAim => m_Wrapper.m_Land_CancelAim;
            public InputAction @Throw => m_Wrapper.m_Land_Throw;
            public InputAction @PickUp => m_Wrapper.m_Land_PickUp;
            public InputAction @Pull => m_Wrapper.m_Land_Pull;
            public InputAction @Dash => m_Wrapper.m_Land_Dash;
            public InputAction @Kick => m_Wrapper.m_Land_Kick;
            public InputAction @Heal => m_Wrapper.m_Land_Heal;
            public InputAction @SpecialAttack_AnchorSpin => m_Wrapper.m_Land_SpecialAttack_AnchorSpin;
            public InputAction @SpecialAttack_ChainSpikes => m_Wrapper.m_Land_SpecialAttack_ChainSpikes;
            public InputAction @NullAction => m_Wrapper.m_Land_NullAction;
            public InputActionMap Get() { return m_Wrapper.m_Land; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(LandActions set) { return set.Get(); }
            public void AddCallbacks(ILandActions instance)
            {
                if (instance == null || m_Wrapper.m_LandActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_LandActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @CancelAim.started += instance.OnCancelAim;
                @CancelAim.performed += instance.OnCancelAim;
                @CancelAim.canceled += instance.OnCancelAim;
                @Throw.started += instance.OnThrow;
                @Throw.performed += instance.OnThrow;
                @Throw.canceled += instance.OnThrow;
                @PickUp.started += instance.OnPickUp;
                @PickUp.performed += instance.OnPickUp;
                @PickUp.canceled += instance.OnPickUp;
                @Pull.started += instance.OnPull;
                @Pull.performed += instance.OnPull;
                @Pull.canceled += instance.OnPull;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Kick.started += instance.OnKick;
                @Kick.performed += instance.OnKick;
                @Kick.canceled += instance.OnKick;
                @Heal.started += instance.OnHeal;
                @Heal.performed += instance.OnHeal;
                @Heal.canceled += instance.OnHeal;
                @SpecialAttack_AnchorSpin.started += instance.OnSpecialAttack_AnchorSpin;
                @SpecialAttack_AnchorSpin.performed += instance.OnSpecialAttack_AnchorSpin;
                @SpecialAttack_AnchorSpin.canceled += instance.OnSpecialAttack_AnchorSpin;
                @SpecialAttack_ChainSpikes.started += instance.OnSpecialAttack_ChainSpikes;
                @SpecialAttack_ChainSpikes.performed += instance.OnSpecialAttack_ChainSpikes;
                @SpecialAttack_ChainSpikes.canceled += instance.OnSpecialAttack_ChainSpikes;
                @NullAction.started += instance.OnNullAction;
                @NullAction.performed += instance.OnNullAction;
                @NullAction.canceled += instance.OnNullAction;
            }

            private void UnregisterCallbacks(ILandActions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Look.started -= instance.OnLook;
                @Look.performed -= instance.OnLook;
                @Look.canceled -= instance.OnLook;
                @Aim.started -= instance.OnAim;
                @Aim.performed -= instance.OnAim;
                @Aim.canceled -= instance.OnAim;
                @CancelAim.started -= instance.OnCancelAim;
                @CancelAim.performed -= instance.OnCancelAim;
                @CancelAim.canceled -= instance.OnCancelAim;
                @Throw.started -= instance.OnThrow;
                @Throw.performed -= instance.OnThrow;
                @Throw.canceled -= instance.OnThrow;
                @PickUp.started -= instance.OnPickUp;
                @PickUp.performed -= instance.OnPickUp;
                @PickUp.canceled -= instance.OnPickUp;
                @Pull.started -= instance.OnPull;
                @Pull.performed -= instance.OnPull;
                @Pull.canceled -= instance.OnPull;
                @Dash.started -= instance.OnDash;
                @Dash.performed -= instance.OnDash;
                @Dash.canceled -= instance.OnDash;
                @Kick.started -= instance.OnKick;
                @Kick.performed -= instance.OnKick;
                @Kick.canceled -= instance.OnKick;
                @Heal.started -= instance.OnHeal;
                @Heal.performed -= instance.OnHeal;
                @Heal.canceled -= instance.OnHeal;
                @SpecialAttack_AnchorSpin.started -= instance.OnSpecialAttack_AnchorSpin;
                @SpecialAttack_AnchorSpin.performed -= instance.OnSpecialAttack_AnchorSpin;
                @SpecialAttack_AnchorSpin.canceled -= instance.OnSpecialAttack_AnchorSpin;
                @SpecialAttack_ChainSpikes.started -= instance.OnSpecialAttack_ChainSpikes;
                @SpecialAttack_ChainSpikes.performed -= instance.OnSpecialAttack_ChainSpikes;
                @SpecialAttack_ChainSpikes.canceled -= instance.OnSpecialAttack_ChainSpikes;
                @NullAction.started -= instance.OnNullAction;
                @NullAction.performed -= instance.OnNullAction;
                @NullAction.canceled -= instance.OnNullAction;
            }

            public void RemoveCallbacks(ILandActions instance)
            {
                if (m_Wrapper.m_LandActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ILandActions instance)
            {
                foreach (var item in m_Wrapper.m_LandActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_LandActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public LandActions @Land => new LandActions(this);

        // UI
        private readonly InputActionMap m_UI;
        private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
        private readonly InputAction m_UI_Back;
        private readonly InputAction m_UI_OpenMenu;
        private readonly InputAction m_UI_Accept;
        private readonly InputAction m_UI_Quit;
        private readonly InputAction m_UI_Debug_UnlockMenu;
        public struct UIActions
        {
            private @PlayerAnchorInputControls m_Wrapper;
            public UIActions(@PlayerAnchorInputControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Back => m_Wrapper.m_UI_Back;
            public InputAction @OpenMenu => m_Wrapper.m_UI_OpenMenu;
            public InputAction @Accept => m_Wrapper.m_UI_Accept;
            public InputAction @Quit => m_Wrapper.m_UI_Quit;
            public InputAction @Debug_UnlockMenu => m_Wrapper.m_UI_Debug_UnlockMenu;
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void AddCallbacks(IUIActions instance)
            {
                if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
                @OpenMenu.started += instance.OnOpenMenu;
                @OpenMenu.performed += instance.OnOpenMenu;
                @OpenMenu.canceled += instance.OnOpenMenu;
                @Accept.started += instance.OnAccept;
                @Accept.performed += instance.OnAccept;
                @Accept.canceled += instance.OnAccept;
                @Quit.started += instance.OnQuit;
                @Quit.performed += instance.OnQuit;
                @Quit.canceled += instance.OnQuit;
                @Debug_UnlockMenu.started += instance.OnDebug_UnlockMenu;
                @Debug_UnlockMenu.performed += instance.OnDebug_UnlockMenu;
                @Debug_UnlockMenu.canceled += instance.OnDebug_UnlockMenu;
            }

            private void UnregisterCallbacks(IUIActions instance)
            {
                @Back.started -= instance.OnBack;
                @Back.performed -= instance.OnBack;
                @Back.canceled -= instance.OnBack;
                @OpenMenu.started -= instance.OnOpenMenu;
                @OpenMenu.performed -= instance.OnOpenMenu;
                @OpenMenu.canceled -= instance.OnOpenMenu;
                @Accept.started -= instance.OnAccept;
                @Accept.performed -= instance.OnAccept;
                @Accept.canceled -= instance.OnAccept;
                @Quit.started -= instance.OnQuit;
                @Quit.performed -= instance.OnQuit;
                @Quit.canceled -= instance.OnQuit;
                @Debug_UnlockMenu.started -= instance.OnDebug_UnlockMenu;
                @Debug_UnlockMenu.performed -= instance.OnDebug_UnlockMenu;
                @Debug_UnlockMenu.canceled -= instance.OnDebug_UnlockMenu;
            }

            public void RemoveCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IUIActions instance)
            {
                foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public UIActions @UI => new UIActions(this);
        private int m_DesktopSchemeIndex = -1;
        public InputControlScheme DesktopScheme
        {
            get
            {
                if (m_DesktopSchemeIndex == -1) m_DesktopSchemeIndex = asset.FindControlSchemeIndex("Desktop");
                return asset.controlSchemes[m_DesktopSchemeIndex];
            }
        }
        public interface ILandActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnAim(InputAction.CallbackContext context);
            void OnCancelAim(InputAction.CallbackContext context);
            void OnThrow(InputAction.CallbackContext context);
            void OnPickUp(InputAction.CallbackContext context);
            void OnPull(InputAction.CallbackContext context);
            void OnDash(InputAction.CallbackContext context);
            void OnKick(InputAction.CallbackContext context);
            void OnHeal(InputAction.CallbackContext context);
            void OnSpecialAttack_AnchorSpin(InputAction.CallbackContext context);
            void OnSpecialAttack_ChainSpikes(InputAction.CallbackContext context);
            void OnNullAction(InputAction.CallbackContext context);
        }
        public interface IUIActions
        {
            void OnBack(InputAction.CallbackContext context);
            void OnOpenMenu(InputAction.CallbackContext context);
            void OnAccept(InputAction.CallbackContext context);
            void OnQuit(InputAction.CallbackContext context);
            void OnDebug_UnlockMenu(InputAction.CallbackContext context);
        }
    }
}
